const SET_CATEGORIES_LIST_DISPLAY = 'SET_CATEGORIES_LIST_DISPLAY';
const SET_PRODUCTS_LIST_DISPLAY = 'SET_PRODUCTS_LIST_DISPLAY';
const SET_PRODUCT_DISPLAY = 'SET_PRODUCT_DISPLAY';

export { SET_CATEGORIES_LIST_DISPLAY, SET_PRODUCTS_LIST_DISPLAY, SET_PRODUCT_DISPLAY };