const SET_CATEGORIES_LIST_DISPLAY = 'SET_CATEGORIES_LIST_DISPLAY';
const SET_PRODUCTS_LIST_DISPLAY = 'SET_PRODUCTS_LIST_DISPLAY';
const SET_PRODUCT_DISPLAY = 'SET_PRODUCT_DISPLAY';
const UPDATE_SEARCH_TERM = 'UPDATE_SEARCH_TERM';

export { SET_CATEGORIES_LIST_DISPLAY, SET_PRODUCTS_LIST_DISPLAY, SET_PRODUCT_DISPLAY, UPDATE_SEARCH_TERM };